{% set version = "0.7.0" %}

package:
  name: dmslogo
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/d/dmslogo/dmslogo-{{ version }}.tar.gz
  sha256: 60100b600effbea54d3e841aba1c51b4148e47d2f06483cf02aa6a06060a1bfb

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - matplotlib-base
    - numpy
    - palettable
    - pandas
    - python >={{ python_min }}

test:
  imports:
    - dmslogo
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jbloomlab/dmslogo
  summary: Logo plots of deep mutational scanning (DMS) data
  license: GPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - danielnachun
